"""
Drug database for the Pharmacy Record Generator.

Contains clinically accurate controlled and non-controlled drug definitions
with realistic dosing, quantities, scheduling, and specialty affinities.

SIMULATED DATA — For compliance training and audit testing only.
"""

from typing import Any, Dict, List

DrugDef = Dict[str, Any]

# ---------------------------------------------------------------------------
# CONTROLLED SUBSTANCES
# ---------------------------------------------------------------------------

CONTROLLED_DRUGS: Dict[str, List[DrugDef]] = {

    # -----------------------------------------------------------------------
    # Schedule II — No refills permitted
    # -----------------------------------------------------------------------
    "CII": [
        {
            "name": "Oxycodone HCl",
            "brand_names": ["OxyContin", "Roxicodone"],
            "search_term": "oxycodone",
            "strengths": ["5mg", "10mg", "15mg", "20mg", "30mg", "40mg", "80mg"],
            "strength_weights": [0.20, 0.25, 0.15, 0.15, 0.10, 0.10, 0.05],
            "dosage_form": "Tablet, Extended Release",
            "typical_quantities": [30, 60, 90, 120],
            "qty_weights": [0.30, 0.35, 0.25, 0.10],
            "days_supply_options": [30],
            "max_refills": 0,
            "diagnoses": [
                "Chronic pain", "Oncology pain",
                "Post-surgical pain", "Neuropathic pain",
            ],
            "specialties": ["Pain Management", "Oncology", "Orthopedics", "Neurology"],
            "patient_age_range": (25, 80),
        },
        {
            "name": "Oxycodone/Acetaminophen",
            "brand_names": ["Percocet", "Endocet", "Roxicet"],
            "search_term": "oxycodone acetaminophen",
            "strengths": ["5/325mg", "7.5/325mg", "10/325mg"],
            "strength_weights": [0.45, 0.30, 0.25],
            "dosage_form": "Tablet",
            "typical_quantities": [30, 60, 90],
            "qty_weights": [0.40, 0.40, 0.20],
            "days_supply_options": [30],
            "max_refills": 0,
            "diagnoses": [
                "Acute pain", "Post-operative pain",
                "Musculoskeletal pain", "Moderate to severe pain",
            ],
            "specialties": ["Pain Management", "Orthopedics", "Primary Care", "Dentistry"],
            "patient_age_range": (18, 75),
        },
        {
            "name": "Hydrocodone Bitartrate ER",
            "brand_names": ["Zohydro ER", "Hysingla ER"],
            "search_term": "hydrocodone",
            "strengths": ["10mg", "20mg", "30mg", "40mg"],
            "strength_weights": [0.40, 0.30, 0.20, 0.10],
            "dosage_form": "Tablet, Extended Release",
            "typical_quantities": [30, 60],
            "qty_weights": [0.60, 0.40],
            "days_supply_options": [30],
            "max_refills": 0,
            "diagnoses": ["Chronic pain", "Moderate to severe pain"],
            "specialties": ["Pain Management", "Primary Care", "Orthopedics"],
            "patient_age_range": (25, 75),
        },
        {
            "name": "Hydrocodone/Acetaminophen",
            "brand_names": ["Norco", "Vicodin", "Lortab"],
            "search_term": "hydrocodone acetaminophen",
            "strengths": ["5/325mg", "7.5/325mg", "10/325mg"],
            "strength_weights": [0.35, 0.35, 0.30],
            "dosage_form": "Tablet",
            "typical_quantities": [30, 60, 90],
            "qty_weights": [0.35, 0.40, 0.25],
            "days_supply_options": [30],
            "max_refills": 0,
            "diagnoses": [
                "Moderate to severe pain", "Dental pain",
                "Post-surgical pain", "Musculoskeletal pain",
            ],
            "specialties": ["Primary Care", "Orthopedics", "Dentistry", "Pain Management"],
            "patient_age_range": (18, 75),
        },
        {
            "name": "Amphetamine Salts",
            "brand_names": ["Adderall", "Adderall XR"],
            "search_term": "amphetamine",
            "strengths": ["5mg", "10mg", "15mg", "20mg", "25mg", "30mg"],
            "strength_weights": [0.10, 0.20, 0.15, 0.30, 0.10, 0.15],
            "dosage_form": "Tablet",
            "typical_quantities": [30, 60],
            "qty_weights": [0.70, 0.30],
            "days_supply_options": [30],
            "max_refills": 0,
            "diagnoses": ["Attention Deficit Hyperactivity Disorder (ADHD)", "Narcolepsy"],
            "specialties": ["Psychiatry", "Neurology", "Primary Care", "Pediatrics"],
            "patient_age_range": (6, 65),
        },
        {
            "name": "Methylphenidate HCl",
            "brand_names": ["Ritalin", "Concerta", "Methylin"],
            "search_term": "methylphenidate",
            "strengths": ["5mg", "10mg", "18mg", "27mg", "36mg", "54mg"],
            "strength_weights": [0.15, 0.20, 0.20, 0.15, 0.20, 0.10],
            "dosage_form": "Tablet, Extended Release",
            "typical_quantities": [30, 60],
            "qty_weights": [0.75, 0.25],
            "days_supply_options": [30],
            "max_refills": 0,
            "diagnoses": [
                "Attention Deficit Hyperactivity Disorder (ADHD)",
                "Attention Deficit Disorder (ADD)",
            ],
            "specialties": ["Psychiatry", "Neurology", "Primary Care", "Pediatrics"],
            "patient_age_range": (6, 60),
        },
        {
            "name": "Fentanyl Transdermal System",
            "brand_names": ["Duragesic"],
            "search_term": "fentanyl transdermal",
            "strengths": ["12mcg/hr", "25mcg/hr", "50mcg/hr", "75mcg/hr", "100mcg/hr"],
            "strength_weights": [0.10, 0.30, 0.35, 0.15, 0.10],
            "dosage_form": "Patch, Extended Release",
            "typical_quantities": [5, 10, 15],
            "qty_weights": [0.30, 0.50, 0.20],
            "days_supply_options": [30],
            "max_refills": 0,
            "diagnoses": ["Chronic pain", "Cancer pain", "Severe chronic pain"],
            "specialties": ["Pain Management", "Oncology", "Palliative Care"],
            "patient_age_range": (30, 85),
        },
        {
            "name": "Morphine Sulfate ER",
            "brand_names": ["MS Contin", "Morphabond ER"],
            "search_term": "morphine sulfate",
            "strengths": ["15mg", "30mg", "60mg", "100mg", "200mg"],
            "strength_weights": [0.25, 0.35, 0.20, 0.15, 0.05],
            "dosage_form": "Tablet, Extended Release",
            "typical_quantities": [60, 120],
            "qty_weights": [0.60, 0.40],
            "days_supply_options": [30],
            "max_refills": 0,
            "diagnoses": ["Chronic pain", "Cancer pain", "Severe chronic pain"],
            "specialties": ["Pain Management", "Oncology", "Palliative Care"],
            "patient_age_range": (30, 85),
        },
        {
            "name": "Oxymorphone HCl ER",
            "brand_names": ["Opana ER"],
            "search_term": "oxymorphone",
            "strengths": ["5mg", "10mg", "20mg", "40mg"],
            "strength_weights": [0.25, 0.35, 0.25, 0.15],
            "dosage_form": "Tablet, Extended Release",
            "typical_quantities": [60, 120],
            "qty_weights": [0.55, 0.45],
            "days_supply_options": [30],
            "max_refills": 0,
            "diagnoses": ["Chronic pain", "Severe pain requiring around-the-clock opioid"],
            "specialties": ["Pain Management", "Oncology"],
            "patient_age_range": (30, 80),
        },
        {
            "name": "Methadone HCl",
            "brand_names": ["Dolophine", "Methadose"],
            "search_term": "methadone",
            "strengths": ["5mg", "10mg", "40mg"],
            "strength_weights": [0.30, 0.50, 0.20],
            "dosage_form": "Tablet",
            "typical_quantities": [30, 60, 90],
            "qty_weights": [0.25, 0.45, 0.30],
            "days_supply_options": [30],
            "max_refills": 0,
            "diagnoses": ["Chronic pain", "Opioid use disorder (pain treatment)"],
            "specialties": ["Pain Management", "Addiction Medicine", "Palliative Care"],
            "patient_age_range": (25, 75),
        },
    ],

    # -----------------------------------------------------------------------
    # Schedule III — Up to 5 refills in 6 months
    # -----------------------------------------------------------------------
    "CIII": [
        {
            "name": "Buprenorphine/Naloxone",
            "brand_names": ["Suboxone", "Zubsolv", "Bunavail"],
            "search_term": "buprenorphine naloxone",
            "strengths": ["2mg/0.5mg", "4mg/1mg", "8mg/2mg", "12mg/3mg"],
            "strength_weights": [0.15, 0.20, 0.45, 0.20],
            "dosage_form": "Film, Sublingual",
            "typical_quantities": [14, 28, 30, 60],
            "qty_weights": [0.10, 0.20, 0.45, 0.25],
            "days_supply_options": [14, 28, 30],
            "max_refills": 5,
            "diagnoses": ["Opioid use disorder", "Opioid dependence"],
            "specialties": ["Addiction Medicine", "Psychiatry", "Primary Care"],
            "patient_age_range": (18, 65),
        },
        {
            "name": "Testosterone Cypionate",
            "brand_names": ["Depo-Testosterone"],
            "search_term": "testosterone cypionate",
            "strengths": ["200mg/mL"],
            "strength_weights": [1.0],
            "dosage_form": "Injection",
            "typical_quantities": [1, 2, 4, 10],
            "qty_weights": [0.20, 0.30, 0.30, 0.20],
            "days_supply_options": [14, 28, 30],
            "max_refills": 5,
            "diagnoses": ["Hypogonadism", "Testosterone deficiency"],
            "specialties": ["Endocrinology", "Urology", "Primary Care"],
            "patient_age_range": (25, 70),
        },
        {
            "name": "Codeine/Acetaminophen",
            "brand_names": ["Tylenol #3", "Tylenol #4"],
            "search_term": "codeine acetaminophen",
            "strengths": ["30mg/300mg", "60mg/300mg"],
            "strength_weights": [0.65, 0.35],
            "dosage_form": "Tablet",
            "typical_quantities": [20, 30, 60],
            "qty_weights": [0.30, 0.45, 0.25],
            "days_supply_options": [7, 10, 30],
            "max_refills": 5,
            "diagnoses": ["Moderate pain", "Dental pain", "Post-surgical pain"],
            "specialties": ["Primary Care", "Dentistry", "Emergency Medicine"],
            "patient_age_range": (18, 70),
        },
    ],

    # -----------------------------------------------------------------------
    # Schedule IV — Up to 5 refills in 6 months
    # -----------------------------------------------------------------------
    "CIV": [
        {
            "name": "Alprazolam",
            "brand_names": ["Xanax", "Xanax XR", "Niravam"],
            "search_term": "alprazolam",
            "strengths": ["0.25mg", "0.5mg", "1mg", "2mg"],
            "strength_weights": [0.20, 0.30, 0.35, 0.15],
            "dosage_form": "Tablet",
            "typical_quantities": [30, 60, 90],
            "qty_weights": [0.40, 0.35, 0.25],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Anxiety disorder", "Panic disorder", "Generalized anxiety disorder (GAD)"],
            "specialties": ["Psychiatry", "Primary Care", "Internal Medicine"],
            "patient_age_range": (18, 75),
        },
        {
            "name": "Clonazepam",
            "brand_names": ["Klonopin"],
            "search_term": "clonazepam",
            "strengths": ["0.5mg", "1mg", "2mg"],
            "strength_weights": [0.35, 0.40, 0.25],
            "dosage_form": "Tablet",
            "typical_quantities": [60, 90, 180],
            "qty_weights": [0.35, 0.45, 0.20],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Anxiety disorder", "Seizure disorder", "Panic disorder"],
            "specialties": ["Psychiatry", "Neurology", "Primary Care"],
            "patient_age_range": (18, 80),
        },
        {
            "name": "Lorazepam",
            "brand_names": ["Ativan"],
            "search_term": "lorazepam",
            "strengths": ["0.5mg", "1mg", "2mg"],
            "strength_weights": [0.25, 0.45, 0.30],
            "dosage_form": "Tablet",
            "typical_quantities": [30, 60, 90],
            "qty_weights": [0.30, 0.45, 0.25],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Anxiety disorder", "Insomnia", "Seizure disorder"],
            "specialties": ["Psychiatry", "Primary Care", "Neurology"],
            "patient_age_range": (20, 75),
        },
        {
            "name": "Diazepam",
            "brand_names": ["Valium"],
            "search_term": "diazepam",
            "strengths": ["2mg", "5mg", "10mg"],
            "strength_weights": [0.20, 0.45, 0.35],
            "dosage_form": "Tablet",
            "typical_quantities": [30, 60, 90],
            "qty_weights": [0.30, 0.40, 0.30],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Anxiety disorder", "Muscle spasm", "Alcohol withdrawal"],
            "specialties": ["Psychiatry", "Primary Care", "Neurology"],
            "patient_age_range": (20, 75),
        },
        {
            "name": "Zolpidem Tartrate",
            "brand_names": ["Ambien", "Ambien CR"],
            "search_term": "zolpidem",
            "strengths": ["5mg", "10mg"],
            "strength_weights": [0.40, 0.60],
            "dosage_form": "Tablet",
            "typical_quantities": [30],
            "qty_weights": [1.0],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Insomnia", "Sleep-onset insomnia", "Sleep maintenance insomnia"],
            "specialties": ["Primary Care", "Psychiatry", "Internal Medicine"],
            "patient_age_range": (25, 80),
        },
        {
            "name": "Tramadol HCl",
            "brand_names": ["Ultram", "ConZip"],
            "search_term": "tramadol",
            "strengths": ["50mg", "100mg"],
            "strength_weights": [0.65, 0.35],
            "dosage_form": "Tablet",
            "typical_quantities": [60, 90, 120],
            "qty_weights": [0.35, 0.40, 0.25],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Moderate pain", "Chronic pain", "Musculoskeletal pain"],
            "specialties": ["Primary Care", "Orthopedics", "Pain Management"],
            "patient_age_range": (20, 75),
        },
        {
            "name": "Carisoprodol",
            "brand_names": ["Soma"],
            "search_term": "carisoprodol",
            "strengths": ["250mg", "350mg"],
            "strength_weights": [0.35, 0.65],
            "dosage_form": "Tablet",
            "typical_quantities": [60, 90, 120],
            "qty_weights": [0.30, 0.40, 0.30],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Muscle spasm", "Musculoskeletal pain", "Acute back pain"],
            "specialties": ["Primary Care", "Orthopedics", "Physical Medicine"],
            "patient_age_range": (20, 70),
        },
        {
            "name": "Temazepam",
            "brand_names": ["Restoril"],
            "search_term": "temazepam",
            "strengths": ["7.5mg", "15mg", "22.5mg", "30mg"],
            "strength_weights": [0.15, 0.40, 0.20, 0.25],
            "dosage_form": "Capsule",
            "typical_quantities": [30],
            "qty_weights": [1.0],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Insomnia", "Transient insomnia", "Short-term insomnia"],
            "specialties": ["Primary Care", "Psychiatry", "Internal Medicine"],
            "patient_age_range": (30, 80),
        },
        {
            "name": "Triazolam",
            "brand_names": ["Halcion"],
            "search_term": "triazolam",
            "strengths": ["0.125mg", "0.25mg"],
            "strength_weights": [0.45, 0.55],
            "dosage_form": "Tablet",
            "typical_quantities": [30],
            "qty_weights": [1.0],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Insomnia"],
            "specialties": ["Primary Care", "Psychiatry"],
            "patient_age_range": (30, 75),
        },
        {
            "name": "Butalbital/Acetaminophen/Caffeine",
            "brand_names": ["Fioricet"],
            "search_term": "butalbital acetaminophen",
            "strengths": ["50mg/325mg/40mg"],
            "strength_weights": [1.0],
            "dosage_form": "Tablet",
            "typical_quantities": [30, 60],
            "qty_weights": [0.60, 0.40],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Tension headache", "Migraine", "Complex headache"],
            "specialties": ["Primary Care", "Neurology", "Internal Medicine"],
            "patient_age_range": (18, 70),
        },
    ],

    # -----------------------------------------------------------------------
    # Schedule V — Up to 5 refills in 6 months
    # -----------------------------------------------------------------------
    "CV": [
        {
            "name": "Pregabalin",
            "brand_names": ["Lyrica", "Lyrica CR"],
            "search_term": "pregabalin",
            "strengths": ["25mg", "50mg", "75mg", "100mg", "150mg", "200mg", "225mg", "300mg"],
            "strength_weights": [0.05, 0.10, 0.20, 0.15, 0.25, 0.10, 0.05, 0.10],
            "dosage_form": "Capsule",
            "typical_quantities": [60, 90, 180],
            "qty_weights": [0.30, 0.45, 0.25],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": [
                "Neuropathic pain", "Fibromyalgia",
                "Seizure disorder", "Generalized anxiety disorder",
            ],
            "specialties": ["Neurology", "Pain Management", "Primary Care", "Rheumatology"],
            "patient_age_range": (20, 80),
        },
        {
            "name": "Promethazine/Codeine",
            "brand_names": ["Phenergan with Codeine"],
            "search_term": "promethazine codeine",
            "strengths": ["6.25mg-10mg/5mL"],
            "strength_weights": [1.0],
            "dosage_form": "Solution",
            "typical_quantities": [120, 240, 473],
            "qty_weights": [0.45, 0.40, 0.15],
            "days_supply_options": [7, 10, 14],
            "max_refills": 5,
            "diagnoses": ["Cough", "Upper respiratory infection", "Bronchitis"],
            "specialties": ["Primary Care", "Internal Medicine"],
            "patient_age_range": (18, 65),
        },
        {
            "name": "Lacosamide",
            "brand_names": ["Vimpat"],
            "search_term": "lacosamide",
            "strengths": ["50mg", "100mg", "150mg", "200mg"],
            "strength_weights": [0.15, 0.30, 0.30, 0.25],
            "dosage_form": "Tablet",
            "typical_quantities": [60, 90],
            "qty_weights": [0.50, 0.50],
            "days_supply_options": [30],
            "max_refills": 5,
            "diagnoses": ["Partial-onset seizures", "Epilepsy"],
            "specialties": ["Neurology", "Primary Care"],
            "patient_age_range": (17, 80),
        },
    ],
}

# ---------------------------------------------------------------------------
# NON-CONTROLLED MEDICATIONS
# ---------------------------------------------------------------------------

NON_CONTROLLED_DRUGS: List[DrugDef] = [
    {
        "name": "Lisinopril",
        "brand_names": ["Zestril", "Prinivil"],
        "search_term": "lisinopril",
        "strengths": ["2.5mg", "5mg", "10mg", "20mg", "40mg"],
        "strength_weights": [0.05, 0.20, 0.30, 0.30, 0.15],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.40, 0.60],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Hypertension", "Heart failure", "Diabetic nephropathy"],
        "specialties": ["Primary Care", "Cardiology", "Internal Medicine", "Nephrology"],
        "patient_age_range": (35, 85),
    },
    {
        "name": "Metformin HCl",
        "brand_names": ["Glucophage", "Fortamet", "Riomet"],
        "search_term": "metformin",
        "strengths": ["500mg", "850mg", "1000mg"],
        "strength_weights": [0.35, 0.25, 0.40],
        "dosage_form": "Tablet",
        "typical_quantities": [60, 90, 180],
        "qty_weights": [0.20, 0.50, 0.30],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Type 2 diabetes mellitus", "Prediabetes", "Insulin resistance"],
        "specialties": ["Primary Care", "Endocrinology", "Internal Medicine"],
        "patient_age_range": (30, 80),
    },
    {
        "name": "Amlodipine Besylate",
        "brand_names": ["Norvasc"],
        "search_term": "amlodipine",
        "strengths": ["2.5mg", "5mg", "10mg"],
        "strength_weights": [0.15, 0.55, 0.30],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.35, 0.65],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Hypertension", "Angina", "Coronary artery disease"],
        "specialties": ["Primary Care", "Cardiology", "Internal Medicine"],
        "patient_age_range": (35, 85),
    },
    {
        "name": "Atorvastatin Calcium",
        "brand_names": ["Lipitor"],
        "search_term": "atorvastatin",
        "strengths": ["10mg", "20mg", "40mg", "80mg"],
        "strength_weights": [0.20, 0.30, 0.30, 0.20],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.35, 0.65],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Hyperlipidemia", "Hypercholesterolemia", "CAD prevention"],
        "specialties": ["Primary Care", "Cardiology", "Internal Medicine"],
        "patient_age_range": (35, 85),
    },
    {
        "name": "Amoxicillin",
        "brand_names": ["Amoxil", "Trimox"],
        "search_term": "amoxicillin",
        "strengths": ["250mg", "500mg", "875mg"],
        "strength_weights": [0.15, 0.45, 0.40],
        "dosage_form": "Capsule",
        "typical_quantities": [20, 21, 28, 30],
        "qty_weights": [0.15, 0.30, 0.25, 0.30],
        "days_supply_options": [7, 10, 14],
        "max_refills": 0,
        "diagnoses": [
            "Bacterial infection", "Acute sinusitis",
            "Dental infection", "Strep throat", "Otitis media",
        ],
        "specialties": ["Primary Care", "Dentistry", "Pediatrics", "Internal Medicine"],
        "patient_age_range": (5, 80),
    },
    {
        "name": "Insulin Glargine",
        "brand_names": ["Lantus", "Basaglar", "Toujeo"],
        "search_term": "insulin glargine",
        "strengths": ["100 units/mL"],
        "strength_weights": [1.0],
        "dosage_form": "Injection",
        "typical_quantities": [3, 5, 10],
        "qty_weights": [0.30, 0.50, 0.20],
        "days_supply_options": [30],
        "max_refills": 11,
        "diagnoses": ["Type 1 diabetes mellitus", "Type 2 diabetes mellitus"],
        "specialties": ["Primary Care", "Endocrinology", "Internal Medicine"],
        "patient_age_range": (15, 80),
    },
    {
        "name": "Levothyroxine Sodium",
        "brand_names": ["Synthroid", "Levoxyl", "Unithroid"],
        "search_term": "levothyroxine",
        "strengths": ["25mcg", "50mcg", "75mcg", "88mcg", "100mcg", "112mcg", "125mcg", "150mcg"],
        "strength_weights": [0.05, 0.20, 0.15, 0.10, 0.20, 0.10, 0.10, 0.10],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.35, 0.65],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Hypothyroidism", "Thyroid disease", "Hashimoto's thyroiditis"],
        "specialties": ["Primary Care", "Endocrinology", "Internal Medicine"],
        "patient_age_range": (25, 85),
    },
    {
        "name": "Metoprolol Succinate",
        "brand_names": ["Toprol-XL"],
        "search_term": "metoprolol succinate",
        "strengths": ["25mg", "50mg", "100mg", "200mg"],
        "strength_weights": [0.20, 0.35, 0.30, 0.15],
        "dosage_form": "Tablet, Extended Release",
        "typical_quantities": [30, 90],
        "qty_weights": [0.35, 0.65],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Hypertension", "Heart failure", "Angina", "Atrial fibrillation"],
        "specialties": ["Primary Care", "Cardiology", "Internal Medicine"],
        "patient_age_range": (35, 85),
    },
    {
        "name": "Sertraline HCl",
        "brand_names": ["Zoloft"],
        "search_term": "sertraline",
        "strengths": ["25mg", "50mg", "100mg"],
        "strength_weights": [0.15, 0.50, 0.35],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.40, 0.60],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Major depressive disorder", "Anxiety disorder", "OCD", "PTSD"],
        "specialties": ["Psychiatry", "Primary Care", "Internal Medicine"],
        "patient_age_range": (18, 75),
    },
    {
        "name": "Omeprazole",
        "brand_names": ["Prilosec"],
        "search_term": "omeprazole",
        "strengths": ["10mg", "20mg", "40mg"],
        "strength_weights": [0.10, 0.55, 0.35],
        "dosage_form": "Capsule, Delayed Release",
        "typical_quantities": [30, 90],
        "qty_weights": [0.40, 0.60],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["GERD", "Peptic ulcer disease", "H. pylori", "Erosive esophagitis"],
        "specialties": ["Primary Care", "Gastroenterology", "Internal Medicine"],
        "patient_age_range": (25, 80),
    },
    {
        "name": "Furosemide",
        "brand_names": ["Lasix"],
        "search_term": "furosemide",
        "strengths": ["20mg", "40mg", "80mg"],
        "strength_weights": [0.30, 0.50, 0.20],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.40, 0.60],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Edema", "Hypertension", "Congestive heart failure", "Renal disease"],
        "specialties": ["Primary Care", "Cardiology", "Nephrology", "Internal Medicine"],
        "patient_age_range": (40, 90),
    },
    {
        "name": "Gabapentin",
        "brand_names": ["Neurontin", "Gralise"],
        "search_term": "gabapentin",
        "strengths": ["100mg", "300mg", "400mg", "600mg", "800mg"],
        "strength_weights": [0.10, 0.30, 0.15, 0.30, 0.15],
        "dosage_form": "Capsule",
        "typical_quantities": [90, 180, 270],
        "qty_weights": [0.35, 0.45, 0.20],
        "days_supply_options": [30],
        "max_refills": 11,
        "diagnoses": [
            "Neuropathic pain", "Seizure disorder",
            "Fibromyalgia", "Post-herpetic neuralgia",
        ],
        "specialties": ["Neurology", "Primary Care", "Pain Management", "Psychiatry"],
        "patient_age_range": (20, 85),
    },
    {
        "name": "Pantoprazole Sodium",
        "brand_names": ["Protonix"],
        "search_term": "pantoprazole",
        "strengths": ["20mg", "40mg"],
        "strength_weights": [0.30, 0.70],
        "dosage_form": "Tablet, Delayed Release",
        "typical_quantities": [30, 90],
        "qty_weights": [0.40, 0.60],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["GERD", "Erosive esophagitis", "Zollinger-Ellison syndrome"],
        "specialties": ["Primary Care", "Gastroenterology", "Internal Medicine"],
        "patient_age_range": (25, 80),
    },
    {
        "name": "Montelukast Sodium",
        "brand_names": ["Singulair"],
        "search_term": "montelukast",
        "strengths": ["4mg", "5mg", "10mg"],
        "strength_weights": [0.10, 0.15, 0.75],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.40, 0.60],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Asthma", "Allergic rhinitis", "Exercise-induced bronchoconstriction"],
        "specialties": ["Primary Care", "Pulmonology", "Allergy", "Pediatrics"],
        "patient_age_range": (2, 75),
    },
    {
        "name": "Albuterol Sulfate",
        "brand_names": ["ProAir HFA", "Ventolin HFA", "Proventil HFA"],
        "search_term": "albuterol",
        "strengths": ["90mcg/actuation"],
        "strength_weights": [1.0],
        "dosage_form": "Inhaler",
        "typical_quantities": [1, 2],
        "qty_weights": [0.70, 0.30],
        "days_supply_options": [30],
        "max_refills": 11,
        "diagnoses": ["Asthma", "COPD", "Bronchospasm"],
        "specialties": ["Primary Care", "Pulmonology", "Allergy", "Pediatrics"],
        "patient_age_range": (5, 85),
    },
    {
        "name": "Losartan Potassium",
        "brand_names": ["Cozaar"],
        "search_term": "losartan",
        "strengths": ["25mg", "50mg", "100mg"],
        "strength_weights": [0.20, 0.50, 0.30],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.35, 0.65],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Hypertension", "Diabetic nephropathy", "Heart failure"],
        "specialties": ["Primary Care", "Cardiology", "Nephrology", "Internal Medicine"],
        "patient_age_range": (35, 85),
    },
    {
        "name": "Azithromycin",
        "brand_names": ["Zithromax", "Z-Pack"],
        "search_term": "azithromycin",
        "strengths": ["250mg", "500mg"],
        "strength_weights": [0.60, 0.40],
        "dosage_form": "Tablet",
        "typical_quantities": [6, 3, 5],
        "qty_weights": [0.50, 0.25, 0.25],
        "days_supply_options": [5, 3, 6],
        "max_refills": 0,
        "diagnoses": [
            "Community-acquired pneumonia", "Acute exacerbation of chronic bronchitis",
            "Sinusitis", "Bacterial infection",
        ],
        "specialties": ["Primary Care", "Internal Medicine", "Pulmonology"],
        "patient_age_range": (5, 80),
    },
    {
        "name": "Clopidogrel Bisulfate",
        "brand_names": ["Plavix"],
        "search_term": "clopidogrel",
        "strengths": ["75mg"],
        "strength_weights": [1.0],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.40, 0.60],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": [
            "ACS prevention", "MI prevention",
            "Stroke prevention", "Peripheral artery disease",
        ],
        "specialties": ["Cardiology", "Neurology", "Primary Care", "Internal Medicine"],
        "patient_age_range": (40, 90),
    },
    {
        "name": "Doxycycline Hyclate",
        "brand_names": ["Vibramycin", "Doryx"],
        "search_term": "doxycycline",
        "strengths": ["50mg", "100mg"],
        "strength_weights": [0.25, 0.75],
        "dosage_form": "Capsule",
        "typical_quantities": [14, 20, 28, 30],
        "qty_weights": [0.25, 0.20, 0.30, 0.25],
        "days_supply_options": [7, 10, 14, 30],
        "max_refills": 0,
        "diagnoses": ["Bacterial infection", "Acne vulgaris", "Lyme disease", "Pneumonia"],
        "specialties": ["Primary Care", "Dermatology", "Infectious Disease"],
        "patient_age_range": (12, 75),
    },
    {
        "name": "Rosuvastatin Calcium",
        "brand_names": ["Crestor", "Ezallor"],
        "search_term": "rosuvastatin",
        "strengths": ["5mg", "10mg", "20mg", "40mg"],
        "strength_weights": [0.15, 0.35, 0.30, 0.20],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.35, 0.65],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Hyperlipidemia", "Hypercholesterolemia", "CAD prevention"],
        "specialties": ["Primary Care", "Cardiology", "Internal Medicine"],
        "patient_age_range": (35, 85),
    },
    {
        "name": "Escitalopram Oxalate",
        "brand_names": ["Lexapro"],
        "search_term": "escitalopram",
        "strengths": ["5mg", "10mg", "20mg"],
        "strength_weights": [0.15, 0.50, 0.35],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.40, 0.60],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Major depressive disorder", "Generalized anxiety disorder"],
        "specialties": ["Psychiatry", "Primary Care", "Internal Medicine"],
        "patient_age_range": (18, 75),
    },
    {
        "name": "Linagliptin",
        "brand_names": ["Tradjenta"],
        "search_term": "linagliptin",
        "strengths": ["5mg"],
        "strength_weights": [1.0],
        "dosage_form": "Tablet",
        "typical_quantities": [30, 90],
        "qty_weights": [0.40, 0.60],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Type 2 diabetes mellitus"],
        "specialties": ["Primary Care", "Endocrinology"],
        "patient_age_range": (35, 80),
    },
    {
        "name": "Alendronate Sodium",
        "brand_names": ["Fosamax"],
        "search_term": "alendronate",
        "strengths": ["5mg", "10mg", "35mg", "70mg"],
        "strength_weights": [0.05, 0.10, 0.35, 0.50],
        "dosage_form": "Tablet",
        "typical_quantities": [4, 12, 30],
        "qty_weights": [0.30, 0.35, 0.35],
        "days_supply_options": [28, 84, 30],
        "max_refills": 11,
        "diagnoses": ["Osteoporosis", "Paget's disease", "Glucocorticoid-induced osteoporosis"],
        "specialties": ["Primary Care", "Rheumatology", "Endocrinology", "Internal Medicine"],
        "patient_age_range": (45, 90),
    },
    {
        "name": "Tamsulosin HCl",
        "brand_names": ["Flomax"],
        "search_term": "tamsulosin",
        "strengths": ["0.4mg"],
        "strength_weights": [1.0],
        "dosage_form": "Capsule, Extended Release",
        "typical_quantities": [30, 90],
        "qty_weights": [0.40, 0.60],
        "days_supply_options": [30, 90],
        "max_refills": 11,
        "diagnoses": ["Benign prostatic hyperplasia (BPH)", "Urinary retention"],
        "specialties": ["Urology", "Primary Care", "Internal Medicine"],
        "patient_age_range": (45, 85),
    },
    {
        "name": "Fluticasone Propionate",
        "brand_names": ["Flonase", "Flovent"],
        "search_term": "fluticasone",
        "strengths": ["50mcg/actuation", "110mcg/actuation", "220mcg/actuation"],
        "strength_weights": [0.50, 0.30, 0.20],
        "dosage_form": "Spray",
        "typical_quantities": [1, 2],
        "qty_weights": [0.65, 0.35],
        "days_supply_options": [30],
        "max_refills": 11,
        "diagnoses": ["Allergic rhinitis", "Asthma", "Nasal polyps"],
        "specialties": ["Primary Care", "Allergy", "Pulmonology", "Pediatrics"],
        "patient_age_range": (4, 80),
    },
    {
        "name": "Prednisone",
        "brand_names": ["Deltasone", "Rayos"],
        "search_term": "prednisone",
        "strengths": ["1mg", "2.5mg", "5mg", "10mg", "20mg", "50mg"],
        "strength_weights": [0.05, 0.10, 0.30, 0.30, 0.20, 0.05],
        "dosage_form": "Tablet",
        "typical_quantities": [6, 12, 21, 30],
        "qty_weights": [0.20, 0.20, 0.30, 0.30],
        "days_supply_options": [6, 12, 21, 30],
        "max_refills": 3,
        "diagnoses": [
            "Inflammatory condition", "Asthma exacerbation",
            "Autoimmune disorder", "Allergic reaction",
        ],
        "specialties": [
            "Primary Care", "Rheumatology", "Pulmonology",
            "Dermatology", "Internal Medicine",
        ],
        "patient_age_range": (18, 85),
    },
]


def get_all_drugs() -> List[DrugDef]:
    """Return flat list of all drug definitions with schedule annotated."""
    all_drugs: List[DrugDef] = []
    for schedule, drugs in CONTROLLED_DRUGS.items():
        for d in drugs:
            drug = dict(d)
            drug["schedule"] = schedule
            all_drugs.append(drug)
    for d in NON_CONTROLLED_DRUGS:
        drug = dict(d)
        drug["schedule"] = "Non-Control"
        all_drugs.append(drug)
    return all_drugs
